/**
 * 26-Week Rolling Block Planner Page
 *
 * Professional operational planning command centre interface for the 26-week
 * rolling maintenance horizon. Integrates with the backend /planner/rolling endpoint
 * (rolling_26week_block_plan.csv) and XAI explainability engine.
 *
 * Data provenance: DERIVED — generated by PlanningService from real railway spatial
 * and timetable constraint data.
 */

import React, { useEffect, useMemo, useState } from "react";
import {
  CalendarRange,
  RefreshCw,
  Search,
  Filter,
  Layers,
  Sparkles,
  CheckCircle2,
  Clock,
  TrendingUp,
  AlertTriangle,
  SlidersHorizontal,
  ChevronDown,
  X,
  ShieldCheck,
  Calendar,
} from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/common/PageHeader";
import { plannerApi, type RollingPlanBlock } from "@/api/plannerApi";
import { RollingBlockCard } from "./RollingBlockCard";
import { RollingBlockDetailDialog } from "./RollingBlockDetailDialog";
import { minutesToDuration } from "@/utils/formatters";
import { sectionById } from "@/data/sections";
import { STATIONS } from "@/data/stations";
import { cn } from "@/lib/utils";

// Map station codes to friendly names
const STATION_NAMES: Record<string, string> = Object.fromEntries(
  STATIONS.map((s) => [s.station_code, s.name]),
);

type SortOption = "week_asc" | "priority_desc" | "section_asc" | "duration_desc";

export function RollingPlanPage() {
  const [items, setItems] = useState<RollingPlanBlock[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [isOptimizing, setIsOptimizing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Filter & Search State
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedWeek, setSelectedWeek] = useState<number | "all">("all");
  const [selectedDept, setSelectedDept] = useState<string>("all");
  const [selectedStatus, setSelectedStatus] = useState<string>("all");
  const [sortBy, setSortBy] = useState<SortOption>("week_asc");

  // Detailed Block Dialog State
  const [selectedBlock, setSelectedBlock] = useState<RollingPlanBlock | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);

  // Fetch Rolling Plan from Backend
  const fetchData = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await plannerApi.getRollingPlan({ page: 1, page_size: 200 });
      const fetched: RollingPlanBlock[] = (res?.items ?? res?.records ?? []) as RollingPlanBlock[];
      setItems(fetched);
      setTotal(res?.total ?? fetched.length);

      // Deep link support: check if URL contains ?block=...
      const urlParams = new URLSearchParams(window.location.search);
      const deepLinkedBlockId = urlParams.get("block");
      if (deepLinkedBlockId) {
        const target = fetched.find((b) => b.block_id === deepLinkedBlockId);
        if (target) {
          setSelectedBlock(target);
          setDialogOpen(true);
        }
      }
    } catch {
      setError("Could not load rolling block plan — backend unavailable.");
      toast.error("Rolling Plan", { description: "Backend unavailable." });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void fetchData();
  }, []);

  // Handle re-running 26-week rolling optimization
  const handleRunOptimization = async () => {
    setIsOptimizing(true);
    try {
      await plannerApi.createMonthlyPlan();
      toast.success("26-Week Rolling Optimization Completed", {
        description: "Regenerated corridor-wide rolling blocks across 26 weeks.",
      });
      await fetchData();
    } catch {
      toast.error("Optimization Failed", {
        description: "Could not execute rolling plan optimization.",
      });
    } finally {
      setIsOptimizing(false);
    }
  };

  // Open Block in Dialog & Update URL
  const handleSelectBlock = (block: RollingPlanBlock) => {
    setSelectedBlock(block);
    setDialogOpen(true);
    const url = new URL(window.location.href);
    url.searchParams.set("block", block.block_id);
    window.history.replaceState({}, "", url.toString());
  };

  // Close Dialog & Clean URL
  const handleDialogOpenChange = (open: boolean) => {
    setDialogOpen(open);
    if (!open) {
      const url = new URL(window.location.href);
      url.searchParams.delete("block");
      window.history.replaceState({}, "", url.toString());
    }
  };

  // Handle local status update from modal (Approve / Reject)
  const handleStatusUpdated = (blockId: string, newStatus: string) => {
    setItems((prev) =>
      prev.map((item) => (item.block_id === blockId ? { ...item, status: newStatus } : item)),
    );
    if (selectedBlock?.block_id === blockId) {
      setSelectedBlock((prev) => (prev ? { ...prev, status: newStatus } : null));
    }
  };

  // Available unique weeks in dataset
  const availableWeeks = useMemo(() => {
    const wks = new Set<number>();
    items.forEach((item) => {
      if (item.week_number) wks.add(Number(item.week_number));
    });
    return Array.from(wks).sort((a, b) => a - b);
  }, [items]);

  // Filtered & Sorted items
  const filteredItems = useMemo(() => {
    return items.filter((item) => {
      // Week filter
      if (selectedWeek !== "all" && item.week_number !== selectedWeek) {
        return false;
      }

      // Department filter
      if (selectedDept !== "all") {
        const depts = (item.departments || "").split(/[;,]/).map((d) => d.trim().toLowerCase());
        if (!depts.includes(selectedDept.toLowerCase())) {
          return false;
        }
      }

      // Status filter
      if (selectedStatus !== "all") {
        if (item.status?.toUpperCase() !== selectedStatus.toUpperCase()) {
          return false;
        }
      }

      // Search Query
      if (searchQuery.trim()) {
        const query = searchQuery.toLowerCase().trim();
        const section = sectionById(item.section_id);
        const fromStation = section?.from_station?.toLowerCase() ?? "";
        const toStation = section?.to_station?.toLowerCase() ?? "";
        const fromName = (STATION_NAMES[section?.from_station ?? ""] || "").toLowerCase();
        const toName = (STATION_NAMES[section?.to_station ?? ""] || "").toLowerCase();

        const matchId = item.block_id.toLowerCase().includes(query);
        const matchSec = item.section_id.toLowerCase().includes(query);
        const matchTasks = (item.task_ids || "").toLowerCase().includes(query);
        const matchDept = (item.departments || "").toLowerCase().includes(query);
        const matchStations =
          fromStation.includes(query) ||
          toStation.includes(query) ||
          fromName.includes(query) ||
          toName.includes(query);

        if (!matchId && !matchSec && !matchTasks && !matchDept && !matchStations) {
          return false;
        }
      }

      return true;
    });
  }, [items, selectedWeek, selectedDept, selectedStatus, searchQuery]);

  // Sorted items
  const sortedItems = useMemo(() => {
    const list = [...filteredItems];
    list.sort((a, b) => {
      switch (sortBy) {
        case "week_asc":
          return (a.week_number ?? 0) - (b.week_number ?? 0);
        case "priority_desc":
          return (
            Number(b.priority ?? b.priority_score ?? 0) -
            Number(a.priority ?? a.priority_score ?? 0)
          );
        case "section_asc":
          return a.section_id.localeCompare(b.section_id);
        case "duration_desc":
          return (b.duration_minutes ?? 0) - (a.duration_minutes ?? 0);
        default:
          return 0;
      }
    });
    return list;
  }, [filteredItems, sortBy]);

  // Group sorted items by week for structured presentation
  const groupedByWeek = useMemo(() => {
    const groups: Record<number, RollingPlanBlock[]> = {};
    for (const item of sortedItems) {
      const wk = item.week_number ?? 1;
      (groups[wk] ??= []).push(item);
    }
    return groups;
  }, [sortedItems]);

  const groupWeeks = Object.keys(groupedByWeek)
    .map(Number)
    .sort((a, b) => a - b);

  // Summary Metrics calculations
  const metrics = useMemo(() => {
    const totalBlocks = items.length;
    const approvedBlocks = items.filter(
      (b) => b.status?.toUpperCase() === "APPROVED" || b.status?.toUpperCase() === "COMPLETED",
    ).length;
    const proposedBlocks = items.filter(
      (b) =>
        b.status?.toUpperCase() === "PROPOSED" ||
        b.status?.toUpperCase() === "AI RECOMMENDED" ||
        b.status?.toUpperCase() === "PENDING APPROVAL",
    ).length;
    const megaBlocks = items.filter((b) => {
      const depts = (b.departments || "").split(/[;,]/).filter(Boolean);
      return depts.length > 1 || (b.maintenance_type || "").includes("MEGA");
    }).length;
    const avgPriority =
      totalBlocks > 0
        ? (
            items.reduce((acc, b) => acc + Number(b.priority ?? b.priority_score ?? 0), 0) /
            totalBlocks
          ).toFixed(1)
        : "0.0";

    return {
      totalBlocks,
      approvedBlocks,
      proposedBlocks,
      megaBlocks,
      avgPriority,
    };
  }, [items]);

  return (
    <div className="flex h-full flex-col overflow-auto bg-background text-foreground">
      {/* Top Page Header */}
      <PageHeader
        title="26-Week Rolling Block Plan"
        description={`${total} corridor maintenance blocks scheduled across a 26-week horizon · Google OR-Tools Multi-Objective MIP Optimization`}
        crumbs={[{ label: "Planner" }, { label: "26-Week Rolling Plan" }]}
        actions={
          <div className="flex items-center gap-2">
            <button
              id="rolling-plan-optimize-btn"
              onClick={() => void handleRunOptimization()}
              disabled={isOptimizing}
              className="flex items-center gap-1.5 rounded border border-primary/40 bg-primary/10 px-3 py-1.5 text-xs font-semibold text-primary transition-colors hover:bg-primary/20 disabled:opacity-50 cursor-pointer"
            >
              <Sparkles className="size-3.5" aria-hidden />
              {isOptimizing ? "Optimizing…" : "Re-run 26W Optimizer"}
            </button>
            <button
              id="rolling-plan-refresh"
              onClick={() => void fetchData()}
              disabled={loading}
              className="flex items-center gap-1.5 rounded border border-border bg-surface px-3 py-1.5 text-xs font-medium text-foreground transition-colors hover:bg-surface-2 cursor-pointer"
            >
              <RefreshCw className={cn("size-3.5", loading && "animate-spin")} aria-hidden />
              Refresh
            </button>
          </div>
        }
      />

      <div className="flex-1 space-y-4 p-4 lg:p-6 max-w-[1700px] w-full mx-auto">
        {/* Error Alert */}
        {error && (
          <div className="rounded-lg border border-warn/40 bg-warn/5 px-4 py-3 text-sm text-warn flex items-center gap-3">
            <AlertTriangle className="size-5 shrink-0" aria-hidden />
            <div>
              <p className="font-semibold">Unable to reach backend</p>
              <p className="text-xs text-muted-foreground">{error}</p>
            </div>
          </div>
        )}

        {/* 5 KPI Summary Cards */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
          <div className="rounded-lg border border-border bg-surface p-3.5 shadow-sm">
            <div className="flex items-center justify-between text-muted-foreground">
              <span className="text-xs font-medium uppercase tracking-wider">Total Blocks</span>
              <CalendarRange className="size-4 text-primary" aria-hidden />
            </div>
            <p className="mt-1.5 text-2xl font-bold font-mono text-foreground">{metrics.totalBlocks}</p>
            <p className="text-[11px] text-muted-foreground mt-0.5">Across 26-week corridor horizon</p>
          </div>

          <div className="rounded-lg border border-border bg-surface p-3.5 shadow-sm">
            <div className="flex items-center justify-between text-muted-foreground">
              <span className="text-xs font-medium uppercase tracking-wider">Approved</span>
              <CheckCircle2 className="size-4 text-ok" aria-hidden />
            </div>
            <div className="mt-1.5 flex items-baseline gap-2">
              <span className="text-2xl font-bold font-mono text-ok">{metrics.approvedBlocks}</span>
              <span className="text-xs text-muted-foreground">
                ({metrics.totalBlocks > 0 ? Math.round((metrics.approvedBlocks / metrics.totalBlocks) * 100) : 0}%)
              </span>
            </div>
            <p className="text-[11px] text-muted-foreground mt-0.5">Approved by human controller</p>
          </div>

          <div className="rounded-lg border border-border bg-surface p-3.5 shadow-sm">
            <div className="flex items-center justify-between text-muted-foreground">
              <span className="text-xs font-medium uppercase tracking-wider">Pending Review</span>
              <Clock className="size-4 text-warn" aria-hidden />
            </div>
            <p className="mt-1.5 text-2xl font-bold font-mono text-warn">{metrics.proposedBlocks}</p>
            <p className="text-[11px] text-muted-foreground mt-0.5">Awaiting CPRC/SrDOM validation</p>
          </div>

          <div className="rounded-lg border border-border bg-surface p-3.5 shadow-sm">
            <div className="flex items-center justify-between text-muted-foreground">
              <span className="text-xs font-medium uppercase tracking-wider">Mega Blocks</span>
              <Layers className="size-4 text-purple-400" aria-hidden />
            </div>
            <p className="mt-1.5 text-2xl font-bold font-mono text-purple-400">{metrics.megaBlocks}</p>
            <p className="text-[11px] text-muted-foreground mt-0.5">Consolidated multi-discipline</p>
          </div>

          <div className="rounded-lg border border-border bg-surface p-3.5 shadow-sm col-span-2 sm:col-span-1">
            <div className="flex items-center justify-between text-muted-foreground">
              <span className="text-xs font-medium uppercase tracking-wider">Avg MDPS Score</span>
              <TrendingUp className="size-4 text-crit" aria-hidden />
            </div>
            <p className="mt-1.5 text-2xl font-bold font-mono text-crit">{metrics.avgPriority}</p>
            <p className="text-[11px] text-muted-foreground mt-0.5">Prioritized defect urgency</p>
          </div>
        </div>

        {/* Filters and Search Workspace Controls */}
        <div className="rounded-lg border border-border bg-surface p-3.5 shadow-sm space-y-3">
          {/* Top Filter Row: Search & Dropdowns */}
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
            {/* Search Input */}
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search by Block ID, Section (e.g. SEC_001), Station (MS, MBM), Task ID, or Department…"
                className="w-full rounded-md border border-border bg-background py-2 pl-9 pr-8 text-xs text-foreground placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
              />
              {searchQuery && (
                <button
                  onClick={() => setSearchQuery("")}
                  className="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                >
                  <X className="size-3.5" aria-hidden />
                </button>
              )}
            </div>

            {/* Dropdown Filters */}
            <div className="flex items-center gap-2 flex-wrap">
              {/* Department Filter */}
              <select
                value={selectedDept}
                onChange={(e) => setSelectedDept(e.target.value)}
                className="rounded-md border border-border bg-background px-2.5 py-2 text-xs text-foreground focus:border-primary focus:outline-none"
              >
                <option value="all">All Departments</option>
                <option value="Engineering">Engineering (Track)</option>
                <option value="TRD">TRD (Traction)</option>
                <option value="S&T">S&T (Signalling)</option>
              </select>

              {/* Status Filter */}
              <select
                value={selectedStatus}
                onChange={(e) => setSelectedStatus(e.target.value)}
                className="rounded-md border border-border bg-background px-2.5 py-2 text-xs text-foreground focus:border-primary focus:outline-none"
              >
                <option value="all">All Statuses</option>
                <option value="PROPOSED">PROPOSED</option>
                <option value="APPROVED">APPROVED</option>
                <option value="SCHEDULED">SCHEDULED</option>
                <option value="COMPLETED">COMPLETED</option>
                <option value="REJECTED">REJECTED</option>
              </select>

              {/* Sort By */}
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value as SortOption)}
                className="rounded-md border border-border bg-background px-2.5 py-2 text-xs text-foreground focus:border-primary focus:outline-none font-medium"
              >
                <option value="week_asc">Sort: Chronological (Week 1–26)</option>
                <option value="priority_desc">Sort: Highest MDPS Priority</option>
                <option value="section_asc">Sort: Corridor Section (North→South)</option>
                <option value="duration_desc">Sort: Longest Duration</option>
              </select>
            </div>
          </div>

          {/* Week Selector Pills */}
          <div className="border-t border-border/50 pt-2.5">
            <div className="flex items-center gap-2 overflow-x-auto pb-1 text-xs no-scrollbar">
              <span className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wider shrink-0 mr-1 flex items-center gap-1">
                <CalendarRange className="size-3 text-primary" aria-hidden /> Weeks:
              </span>
              <button
                onClick={() => setSelectedWeek("all")}
                className={cn(
                  "rounded-full px-3 py-1 text-xs font-semibold whitespace-nowrap transition-colors border",
                  selectedWeek === "all"
                    ? "bg-primary text-primary-foreground border-primary"
                    : "bg-surface-2 text-muted-foreground border-border hover:bg-surface-2/80 hover:text-foreground",
                )}
              >
                All Weeks ({items.length})
              </button>
              {availableWeeks.map((wk) => {
                const count = items.filter((i) => i.week_number === wk).length;
                return (
                  <button
                    key={wk}
                    onClick={() => setSelectedWeek(wk)}
                    className={cn(
                      "rounded-full px-2.5 py-1 text-xs font-medium whitespace-nowrap transition-colors border flex items-center gap-1.5",
                      selectedWeek === wk
                        ? "bg-primary text-primary-foreground border-primary font-semibold"
                        : "bg-surface-2 text-muted-foreground border-border hover:bg-surface-2/80 hover:text-foreground",
                    )}
                  >
                    <span>Wk {wk}</span>
                    <span
                      className={cn(
                        "rounded-full px-1.5 py-0.2 text-[9px]",
                        selectedWeek === wk
                          ? "bg-black/20 text-white"
                          : "bg-surface text-muted-foreground",
                      )}
                    >
                      {count}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Filter Results Status Bar */}
        <div className="flex items-center justify-between text-xs text-muted-foreground px-1">
          <p>
            Showing <strong className="text-foreground">{sortedItems.length}</strong> of{" "}
            <strong className="text-foreground">{total}</strong> rolling blocks
            {selectedWeek !== "all" && <span> · Week {selectedWeek}</span>}
            {selectedDept !== "all" && <span> · Dept: {selectedDept}</span>}
            {selectedStatus !== "all" && <span> · Status: {selectedStatus}</span>}
            {searchQuery && <span> · Filtered by &ldquo;{searchQuery}&rdquo;</span>}
          </p>
          {(selectedWeek !== "all" || selectedDept !== "all" || selectedStatus !== "all" || searchQuery) && (
            <button
              onClick={() => {
                setSelectedWeek("all");
                setSelectedDept("all");
                setSelectedStatus("all");
                setSearchQuery("");
              }}
              className="text-primary hover:underline font-medium text-xs flex items-center gap-1"
            >
              Reset Filters
            </button>
          )}
        </div>

        {/* Loading State */}
        {loading && items.length === 0 && (
          <div className="py-20 text-center space-y-3">
            <RefreshCw className="size-8 mx-auto animate-spin text-primary" aria-hidden />
            <p className="text-sm font-medium text-foreground">Loading 26-week rolling block plan…</p>
            <p className="text-xs text-muted-foreground">Synthesizing corridor schedule from backend records</p>
          </div>
        )}

        {/* Empty State */}
        {!loading && sortedItems.length === 0 && (
          <div className="flex flex-col items-center gap-3 rounded-lg border border-border bg-surface py-20 text-center">
            <CalendarRange className="size-12 text-muted-foreground/60" aria-hidden />
            <p className="font-semibold text-base text-foreground">No matching blocks found</p>
            <p className="max-w-md text-xs text-muted-foreground">
              No rolling blocks match your current filter criteria. Try clearing search keywords or selecting
              &ldquo;All Weeks&rdquo;.
            </p>
            <button
              onClick={() => {
                setSelectedWeek("all");
                setSelectedDept("all");
                setSelectedStatus("all");
                setSearchQuery("");
              }}
              className="mt-2 rounded border border-border bg-surface px-4 py-2 text-xs font-semibold text-foreground hover:bg-surface-2 transition-colors"
            >
              Clear All Filters
            </button>
          </div>
        )}

        {/* Block Grid: Grouped by Week */}
        {selectedWeek === "all" && groupWeeks.length > 0 && (
          <div className="space-y-6">
            {groupWeeks.map((wk) => {
              const weekBlocks = groupedByWeek[wk] ?? [];
              const weekTotalDuration = weekBlocks.reduce(
                (acc, b) => acc + (b.duration_minutes ?? 0),
                0,
              );
              const firstBlockDate = weekBlocks[0]?.plan_date;

              return (
                <section key={wk} className="space-y-3">
                  {/* Week Group Header Banner */}
                  <div className="flex items-center justify-between gap-3 border-b border-border pb-2">
                    <div className="flex items-center gap-2">
                      <div className="flex size-6 items-center justify-center rounded-md bg-primary/10 text-primary font-mono text-xs font-bold">
                        W{wk}
                      </div>
                      <h2 className="text-sm font-bold tracking-tight text-foreground">
                        Week {wk} Maintenance Window
                      </h2>
                      {firstBlockDate && (
                        <span className="text-xs text-muted-foreground font-mono">
                          · {firstBlockDate}
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-2 text-xs text-muted-foreground">
                      <span className="rounded bg-surface-2 px-2 py-0.5 font-medium border border-border">
                        {weekBlocks.length} block{weekBlocks.length > 1 ? "s" : ""}
                      </span>
                      <span>Total: <strong className="text-foreground">{minutesToDuration(weekTotalDuration)}</strong></span>
                    </div>
                  </div>

                  {/* Cards Grid */}
                  <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
                    {weekBlocks.map((block) => (
                      <RollingBlockCard
                        key={block.block_id}
                        block={block}
                        onSelect={handleSelectBlock}
                        isSelected={selectedBlock?.block_id === block.block_id && dialogOpen}
                      />
                    ))}
                  </div>
                </section>
              );
            })}
          </div>
        )}

        {/* Block Grid: Single Week Focused View */}
        {selectedWeek !== "all" && sortedItems.length > 0 && (
          <div className="space-y-4">
            <div className="flex items-center justify-between gap-3 border-b border-border pb-3">
              <div className="flex items-center gap-2">
                <div className="flex size-7 items-center justify-center rounded-md bg-primary text-primary-foreground font-mono text-sm font-bold">
                  W{selectedWeek}
                </div>
                <div>
                  <h2 className="text-base font-bold text-foreground">
                    Week {selectedWeek} Operational Maintenance Windows
                  </h2>
                  <p className="text-xs text-muted-foreground">
                    {sortedItems.length} blocks scheduled for execution in Week {selectedWeek}
                  </p>
                </div>
              </div>
              <span className="text-xs text-muted-foreground">
                Total Allocated Time:{" "}
                <strong className="text-foreground font-mono">
                  {minutesToDuration(
                    sortedItems.reduce((acc, b) => acc + (b.duration_minutes ?? 0), 0),
                  )}
                </strong>
              </span>
            </div>

            <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
              {sortedItems.map((block) => (
                <RollingBlockCard
                  key={block.block_id}
                  block={block}
                  onSelect={handleSelectBlock}
                  isSelected={selectedBlock?.block_id === block.block_id && dialogOpen}
                />
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Detailed Block Inspection Modal */}
      <RollingBlockDetailDialog
        block={selectedBlock}
        open={dialogOpen}
        onOpenChange={handleDialogOpenChange}
        onStatusUpdated={handleStatusUpdated}
      />
    </div>
  );
}
