/**
 * 26-Week Rolling Block Planner Page
 *
 * Operational planning command centre interface for the 26-week rolling maintenance horizon.
 * Integrates with backend /planner/rolling endpoint (rolling_26week_block_plan.csv) and XAI engine.
 *
 * Data provenance: DERIVED — generated by PlanningService from real railway spatial
 * and timetable constraint data.
 */

import React, { useEffect, useMemo, useState } from "react";
import {
  CalendarRange,
  RefreshCw,
  Search,
  Filter,
  Layers,
  Sparkles,
  CheckCircle2,
  Clock,
  TrendingUp,
  AlertTriangle,
  X,
  Calendar,
  RotateCcw,
  SlidersHorizontal,
  PlusCircle,
} from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/common/PageHeader";
import { plannerApi, type RollingPlanBlock } from "@/api/plannerApi";
import { RollingBlockCard } from "./RollingBlockCard";
import { RollingBlockDetailDialog } from "./RollingBlockDetailDialog";
import { CreateBlockModal } from "./CreateBlockModal";
import { minutesToDuration } from "@/utils/formatters";
import { sectionById } from "@/data/sections";
import { STATIONS } from "@/data/stations";
import { cn } from "@/lib/utils";

// Map station codes to friendly names
const STATION_NAMES: Record<string, string> = Object.fromEntries(
  STATIONS.map((s) => [s.station_code, s.name]),
);

type SortOption = "week_asc" | "date_asc" | "priority_desc" | "duration_desc" | "block_id_asc";
type PriorityFilter = "all" | "critical" | "high" | "medium" | "low";

export function RollingPlanPage() {
  const [items, setItems] = useState<RollingPlanBlock[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [isOptimizing, setIsOptimizing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Filter & Search State
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedWeek, setSelectedWeek] = useState<number | "all">("all");
  const [selectedDept, setSelectedDept] = useState<string>("all");
  const [selectedStatus, setSelectedStatus] = useState<string>("all");
  const [selectedPriority, setSelectedPriority] = useState<PriorityFilter>("all");
  const [startDate, setStartDate] = useState<string>("");
  const [endDate, setEndDate] = useState<string>("");
  const [sortBy, setSortBy] = useState<SortOption>("week_asc");

  // Detailed Block Dialog State
  const [selectedBlock, setSelectedBlock] = useState<RollingPlanBlock | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [createBlockModalOpen, setCreateBlockModalOpen] = useState(false);

  // Fetch Rolling Plan from Backend
  const fetchData = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await plannerApi.getRollingPlan({ page: 1, page_size: 300 });
      const fetched: RollingPlanBlock[] = (res?.items ?? res?.records ?? []) as RollingPlanBlock[];
      setItems(fetched);
      setTotal(res?.total ?? fetched.length);

      // Deep link support: check if URL contains ?block=...
      const urlParams = new URLSearchParams(window.location.search);
      const deepLinkedBlockId = urlParams.get("block");
      if (deepLinkedBlockId) {
        const target = fetched.find((b) => b.block_id === deepLinkedBlockId);
        if (target) {
          setSelectedBlock(target);
          setDialogOpen(true);
        }
      }
    } catch {
      setError("Could not load rolling block plan — backend unavailable.");
      toast.error("Rolling Plan", { description: "Backend unavailable." });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void fetchData();
  }, []);

  // Handle re-running 26-week rolling optimization
  const handleRunOptimization = async () => {
    setIsOptimizing(true);
    try {
      await plannerApi.createRollingPlan();
      toast.success("26-Week Rolling Optimization Completed", {
        description: "Regenerated corridor-wide rolling blocks across 26 weeks.",
      });
      await fetchData();
    } catch {
      toast.error("Optimization Failed", {
        description: "Could not execute rolling plan optimization.",
      });
    } finally {
      setIsOptimizing(false);
    }
  };

  // Open Block in Dialog & Update URL
  const handleSelectBlock = (block: RollingPlanBlock) => {
    setSelectedBlock(block);
    setDialogOpen(true);
    const url = new URL(window.location.href);
    url.searchParams.set("block", block.block_id);
    window.history.replaceState({}, "", url.toString());
  };

  // Close Dialog & Clean URL
  const handleDialogOpenChange = (open: boolean) => {
    setDialogOpen(open);
    if (!open) {
      const url = new URL(window.location.href);
      url.searchParams.delete("block");
      window.history.replaceState({}, "", url.toString());
    }
  };

  // Handle local status update from modal (Approve / Reject)
  const handleStatusUpdated = (blockId: string, newStatus: string) => {
    setItems((prev) =>
      prev.map((item) => (item.block_id === blockId ? { ...item, status: newStatus } : item)),
    );
    if (selectedBlock?.block_id === blockId) {
      setSelectedBlock((prev) => (prev ? { ...prev, status: newStatus } : null));
    }
  };

  // Available unique weeks in dataset (1 to 26)
  const availableWeeks = useMemo(() => {
    const wks = new Set<number>();
    items.forEach((item) => {
      if (item.week_number) wks.add(Number(item.week_number));
    });
    // Ensure all 26 weeks option set if available
    for (let w = 1; w <= 26; w++) wks.add(w);
    return Array.from(wks).sort((a, b) => a - b);
  }, [items]);

  // Clear all filters
  const handleClearFilters = () => {
    setSearchQuery("");
    setSelectedWeek("all");
    setSelectedDept("all");
    setSelectedStatus("all");
    setSelectedPriority("all");
    setStartDate("");
    setEndDate("");
    setSortBy("week_asc");
  };

  const hasActiveFilters =
    searchQuery.trim() !== "" ||
    selectedWeek !== "all" ||
    selectedDept !== "all" ||
    selectedStatus !== "all" ||
    selectedPriority !== "all" ||
    startDate !== "" ||
    endDate !== "";

  // Filtered items
  const filteredItems = useMemo(() => {
    return items.filter((item) => {
      // 1. Week filter
      if (selectedWeek !== "all" && Number(item.week_number) !== Number(selectedWeek)) {
        return false;
      }

      // 2. Department filter
      if (selectedDept !== "all") {
        const depts = (item.departments || "").split(/[;,]/).map((d) => d.trim().toLowerCase());
        const targetDept = selectedDept.toLowerCase();
        if (targetDept === "engineering") {
          if (!depts.some((d) => d.includes("eng") || d.includes("p-way") || d.includes("track"))) {
            return false;
          }
        } else if (!depts.some((d) => d.includes(targetDept))) {
          return false;
        }
      }

      // 3. Status filter
      if (selectedStatus !== "all") {
        const statusUpper = (item.status || "").toUpperCase();
        const targetUpper = selectedStatus.toUpperCase();
        if (targetUpper === "PLANNED") {
          if (statusUpper !== "PLANNED" && statusUpper !== "PROPOSED" && statusUpper !== "SCHEDULED") {
            return false;
          }
        } else if (targetUpper === "PENDING APPROVAL") {
          if (statusUpper !== "PENDING APPROVAL" && statusUpper !== "PROPOSED" && statusUpper !== "AI RECOMMENDED") {
            return false;
          }
        } else if (targetUpper === "CANCELLED") {
          if (statusUpper !== "CANCELLED" && statusUpper !== "REJECTED") {
            return false;
          }
        } else if (statusUpper !== targetUpper) {
          return false;
        }
      }

      // 4. Priority filter
      if (selectedPriority !== "all") {
        const prioScore = Number(item.priority ?? item.priority_score ?? 0);
        if (selectedPriority === "critical" && prioScore < 85) return false;
        if (selectedPriority === "high" && (prioScore < 70 || prioScore >= 85)) return false;
        if (selectedPriority === "medium" && (prioScore < 50 || prioScore >= 70)) return false;
        if (selectedPriority === "low" && prioScore >= 50) return false;
      }

      // 5. Date Range filter
      if (startDate && item.plan_date) {
        if (item.plan_date < startDate) return false;
      }
      if (endDate && item.plan_date) {
        if (item.plan_date > endDate) return false;
      }

      // 6. Search Query
      if (searchQuery.trim()) {
        const query = searchQuery.toLowerCase().trim();
        const section = sectionById(item.section_id);
        const fromStation = section?.from_station?.toLowerCase() ?? "";
        const toStation = section?.to_station?.toLowerCase() ?? "";
        const fromName = (STATION_NAMES[section?.from_station ?? ""] || "").toLowerCase();
        const toName = (STATION_NAMES[section?.to_station ?? ""] || "").toLowerCase();
        const corridorStr = `${fromStation}-${toStation} ${fromName}-${toName} chennai egmore thoothukudi corridor`;

        const matchId = item.block_id.toLowerCase().includes(query);
        const matchSec = item.section_id.toLowerCase().includes(query);
        const matchTasks = (item.task_ids || "").toLowerCase().includes(query);
        const matchDept = (item.departments || "").toLowerCase().includes(query);
        const matchCorridor = corridorStr.includes(query);
        const matchStations =
          fromStation.includes(query) ||
          toStation.includes(query) ||
          fromName.includes(query) ||
          toName.includes(query);

        if (!matchId && !matchSec && !matchTasks && !matchDept && !matchCorridor && !matchStations) {
          return false;
        }
      }

      return true;
    });
  }, [items, selectedWeek, selectedDept, selectedStatus, selectedPriority, startDate, endDate, searchQuery]);

  // Sorted items
  const sortedItems = useMemo(() => {
    const list = [...filteredItems];
    list.sort((a, b) => {
      switch (sortBy) {
        case "week_asc":
          return (a.week_number ?? 0) - (b.week_number ?? 0);
        case "date_asc":
          return (a.plan_date || "").localeCompare(b.plan_date || "");
        case "priority_desc":
          return (
            Number(b.priority ?? b.priority_score ?? 0) -
            Number(a.priority ?? a.priority_score ?? 0)
          );
        case "duration_desc":
          return (b.duration_minutes ?? 0) - (a.duration_minutes ?? 0);
        case "block_id_asc":
          return a.block_id.localeCompare(b.block_id);
        default:
          return 0;
      }
    });
    return list;
  }, [filteredItems, sortBy]);

  // Group sorted items by week for structured presentation
  const groupedByWeek = useMemo(() => {
    const groups: Record<number, RollingPlanBlock[]> = {};
    for (const item of sortedItems) {
      const wk = item.week_number ?? 1;
      (groups[wk] ??= []).push(item);
    }
    return groups;
  }, [sortedItems]);

  const groupWeeks = Object.keys(groupedByWeek)
    .map(Number)
    .sort((a, b) => a - b);

  // Active Filter Summary String
  const filterTagsSummary = useMemo(() => {
    const tags: string[] = [];
    if (selectedWeek !== "all") tags.push(`Week ${selectedWeek}`);
    if (selectedDept !== "all") {
      tags.push(
        selectedDept === "Engineering" ? "Engineering / P-Way" : selectedDept,
      );
    }
    if (selectedStatus !== "all") tags.push(selectedStatus);
    if (selectedPriority !== "all") {
      tags.push(`${selectedPriority.charAt(0).toUpperCase() + selectedPriority.slice(1)} Priority`);
    }
    if (startDate || endDate) {
      tags.push(`Date: ${startDate || "Start"} to ${endDate || "End"}`);
    }
    if (searchQuery.trim()) tags.push(`"${searchQuery.trim()}"`);
    return tags.join(" • ");
  }, [selectedWeek, selectedDept, selectedStatus, selectedPriority, startDate, endDate, searchQuery]);

  // Summary Metrics calculations
  const metrics = useMemo(() => {
    const totalBlocks = items.length;
    const approvedBlocks = items.filter(
      (b) => b.status?.toUpperCase() === "APPROVED" || b.status?.toUpperCase() === "COMPLETED",
    ).length;
    const proposedBlocks = items.filter(
      (b) =>
        b.status?.toUpperCase() === "PROPOSED" ||
        b.status?.toUpperCase() === "AI RECOMMENDED" ||
        b.status?.toUpperCase() === "PENDING APPROVAL",
    ).length;
    const megaBlocks = items.filter((b) => {
      const depts = (b.departments || "").split(/[;,]/).filter(Boolean);
      return depts.length > 1 || (b.maintenance_type || "").includes("MEGA");
    }).length;
    const avgPriority =
      totalBlocks > 0
        ? (
            items.reduce((acc, b) => acc + Number(b.priority ?? b.priority_score ?? 0), 0) /
            totalBlocks
          ).toFixed(1)
        : "0.0";

    return {
      totalBlocks,
      approvedBlocks,
      proposedBlocks,
      megaBlocks,
      avgPriority,
    };
  }, [items]);

  return (
    <div className="flex h-full flex-col overflow-auto bg-background text-foreground">
      {/* Top Page Header */}
      <PageHeader
        title="26-Week Rolling Block Plan"
        description={`${total} corridor maintenance blocks scheduled across a 26-week horizon · Google OR-Tools Multi-Objective MIP Optimization`}
        crumbs={[{ label: "Planner" }, { label: "26-Week Rolling Plan" }]}
        actions={
          <div className="flex items-center gap-2.5">
            <button
              id="rolling-plan-optimize-btn"
              onClick={() => void handleRunOptimization()}
              disabled={isOptimizing}
              className="flex items-center gap-1.5 rounded border border-primary/40 bg-primary/10 px-3 py-1.5 text-xs font-semibold text-primary transition-colors hover:bg-primary/20 disabled:opacity-50 cursor-pointer"
            >
              <Sparkles className="size-3.5" aria-hidden />
              {isOptimizing ? "Optimizing…" : "Re-run 26W Optimizer"}
            </button>
            <button
              id="rolling-plan-refresh"
              onClick={() => void fetchData()}
              disabled={loading}
              className="flex items-center gap-1.5 rounded border border-border bg-surface px-3 py-1.5 text-xs font-medium text-foreground transition-colors hover:bg-surface-2 cursor-pointer"
            >
              <RefreshCw className={cn("size-3.5", loading && "animate-spin")} aria-hidden />
              Refresh
            </button>
            <button
              id="rolling-plan-create-block-btn"
              onClick={() => setCreateBlockModalOpen(true)}
              className="ml-2 flex items-center gap-2 rounded-lg border border-primary bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground shadow-md transition-all duration-200 hover:bg-primary/90 hover:shadow-lg hover:-translate-y-0.5 active:translate-y-0 cursor-pointer ring-2 ring-primary/30"
            >
              <PlusCircle className="size-4.5" aria-hidden />
              Create Block
            </button>
          </div>
        }
      />

      <div className="flex-1 space-y-4 p-4 lg:p-6 max-w-[1700px] w-full mx-auto">
        {/* Error Alert */}
        {error && (
          <div className="rounded-lg border border-warn/40 bg-warn/5 px-4 py-3 text-sm text-warn flex items-center gap-3">
            <AlertTriangle className="size-5 shrink-0" aria-hidden />
            <div>
              <p className="font-semibold">Unable to reach backend</p>
              <p className="text-xs text-muted-foreground">{error}</p>
            </div>
          </div>
        )}

        {/* 5 KPI Summary Cards */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
          <div className="rounded-lg border border-border bg-surface p-3.5 shadow-sm">
            <div className="flex items-center justify-between text-muted-foreground">
              <span className="text-xs font-medium uppercase tracking-wider">Total Blocks</span>
              <CalendarRange className="size-4 text-primary" aria-hidden />
            </div>
            <p className="mt-1.5 text-2xl font-bold font-mono text-foreground">{metrics.totalBlocks}</p>
            <p className="text-[11px] text-muted-foreground mt-0.5">Across 26-week corridor horizon</p>
          </div>

          <div className="rounded-lg border border-border bg-surface p-3.5 shadow-sm">
            <div className="flex items-center justify-between text-muted-foreground">
              <span className="text-xs font-medium uppercase tracking-wider">Approved</span>
              <CheckCircle2 className="size-4 text-ok" aria-hidden />
            </div>
            <div className="mt-1.5 flex items-baseline gap-2">
              <span className="text-2xl font-bold font-mono text-ok">{metrics.approvedBlocks}</span>
              <span className="text-xs text-muted-foreground">
                ({metrics.totalBlocks > 0 ? Math.round((metrics.approvedBlocks / metrics.totalBlocks) * 100) : 0}%)
              </span>
            </div>
            <p className="text-[11px] text-muted-foreground mt-0.5">Approved by human controller</p>
          </div>

          <div className="rounded-lg border border-border bg-surface p-3.5 shadow-sm">
            <div className="flex items-center justify-between text-muted-foreground">
              <span className="text-xs font-medium uppercase tracking-wider">Pending Review</span>
              <Clock className="size-4 text-warn" aria-hidden />
            </div>
            <p className="mt-1.5 text-2xl font-bold font-mono text-warn">{metrics.proposedBlocks}</p>
            <p className="text-[11px] text-muted-foreground mt-0.5">Awaiting CPRC/SrDOM validation</p>
          </div>

          <div className="rounded-lg border border-border bg-surface p-3.5 shadow-sm">
            <div className="flex items-center justify-between text-muted-foreground">
              <span className="text-xs font-medium uppercase tracking-wider">Mega Blocks</span>
              <Layers className="size-4 text-purple-400" aria-hidden />
            </div>
            <p className="mt-1.5 text-2xl font-bold font-mono text-purple-400">{metrics.megaBlocks}</p>
            <p className="text-[11px] text-muted-foreground mt-0.5">Consolidated multi-discipline</p>
          </div>

          <div className="rounded-lg border border-border bg-surface p-3.5 shadow-sm col-span-2 sm:col-span-1">
            <div className="flex items-center justify-between text-muted-foreground">
              <span className="text-xs font-medium uppercase tracking-wider">Avg MDPS Score</span>
              <TrendingUp className="size-4 text-crit" aria-hidden />
            </div>
            <p className="mt-1.5 text-2xl font-bold font-mono text-crit">{metrics.avgPriority}</p>
            <p className="text-[11px] text-muted-foreground mt-0.5">Prioritized defect urgency</p>
          </div>
        </div>

        {/* Filter and Search Toolbar */}
        <div className="rounded-lg border border-border bg-surface p-4 shadow-sm space-y-3.5">
          <div className="flex items-center justify-between border-b border-border/60 pb-2.5">
            <div className="flex items-center gap-2">
              <SlidersHorizontal className="size-4 text-primary" aria-hidden />
              <h2 className="text-xs font-bold uppercase tracking-wider text-foreground">
                Filter & Search Toolbar
              </h2>
            </div>
            {hasActiveFilters && (
              <button
                onClick={handleClearFilters}
                className="flex items-center gap-1 text-xs font-semibold text-primary hover:text-primary/80 transition-colors cursor-pointer"
              >
                <RotateCcw className="size-3.5" aria-hidden />
                Clear Filters
              </button>
            )}
          </div>

          {/* Row 1: Search Input */}
          <div className="relative w-full">
            <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search block ID, corridor, station..."
              className="w-full rounded-md border border-border bg-background py-2 pl-9 pr-8 text-xs text-foreground placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery("")}
                className="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground cursor-pointer"
              >
                <X className="size-3.5" aria-hidden />
              </button>
            )}
          </div>

          {/* Row 2: Select Filters Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-2.5">
            {/* 1. Week Filter */}
            <div>
              <label className="block text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">
                Week Filter
              </label>
              <select
                value={selectedWeek}
                onChange={(e) => setSelectedWeek(e.target.value === "all" ? "all" : Number(e.target.value))}
                className="w-full rounded-md border border-border bg-background px-2.5 py-1.5 text-xs text-foreground focus:border-primary focus:outline-none"
              >
                <option value="all">All Weeks</option>
                {availableWeeks.map((wk) => (
                  <option key={wk} value={wk}>
                    Week {wk}
                  </option>
                ))}
              </select>
            </div>

            {/* 2. Department Filter */}
            <div>
              <label className="block text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">
                Department
              </label>
              <select
                value={selectedDept}
                onChange={(e) => setSelectedDept(e.target.value)}
                className="w-full rounded-md border border-border bg-background px-2.5 py-1.5 text-xs text-foreground focus:border-primary focus:outline-none"
              >
                <option value="all">All Departments</option>
                <option value="Engineering">Engineering / P-Way</option>
                <option value="TRD">TRD</option>
                <option value="S&T">S&T</option>
              </select>
            </div>

            {/* 3. Status Filter */}
            <div>
              <label className="block text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">
                Status
              </label>
              <select
                value={selectedStatus}
                onChange={(e) => setSelectedStatus(e.target.value)}
                className="w-full rounded-md border border-border bg-background px-2.5 py-1.5 text-xs text-foreground focus:border-primary focus:outline-none"
              >
                <option value="all">All Status</option>
                <option value="PLANNED">Planned</option>
                <option value="APPROVED">Approved</option>
                <option value="PENDING APPROVAL">Pending Approval</option>
                <option value="COMPLETED">Completed</option>
                <option value="DEFERRED">Deferred</option>
                <option value="CANCELLED">Cancelled</option>
              </select>
            </div>

            {/* 4. Priority Filter */}
            <div>
              <label className="block text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">
                Priority
              </label>
              <select
                value={selectedPriority}
                onChange={(e) => setSelectedPriority(e.target.value as PriorityFilter)}
                className="w-full rounded-md border border-border bg-background px-2.5 py-1.5 text-xs text-foreground focus:border-primary focus:outline-none"
              >
                <option value="all">All Priorities</option>
                <option value="critical">Critical (85+)</option>
                <option value="high">High (70-84)</option>
                <option value="medium">Medium (50-69)</option>
                <option value="low">Low (&lt;50)</option>
              </select>
            </div>

            {/* 5. Date Range Start & End */}
            <div className="col-span-1 sm:col-span-2 lg:col-span-2 xl:col-span-2 grid grid-cols-2 gap-2">
              <div>
                <label className="block text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">
                  Start Date
                </label>
                <input
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                  className="w-full rounded-md border border-border bg-background px-2 py-1 text-xs text-foreground focus:border-primary focus:outline-none"
                />
              </div>
              <div>
                <label className="block text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">
                  End Date
                </label>
                <input
                  type="date"
                  value={endDate}
                  onChange={(e) => setEndDate(e.target.value)}
                  className="w-full rounded-md border border-border bg-background px-2 py-1 text-xs text-foreground focus:border-primary focus:outline-none"
                />
              </div>
            </div>
          </div>

          {/* Row 3: Sort By & Quick Week Pills */}
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-2.5 border-t border-border/50 pt-2.5">
            <div className="flex items-center gap-2 overflow-x-auto w-full md:w-auto pb-1 md:pb-0 no-scrollbar">
              <span className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wider shrink-0 mr-1 flex items-center gap-1">
                <CalendarRange className="size-3 text-primary" aria-hidden /> Quick Select:
              </span>
              <button
                onClick={() => setSelectedWeek("all")}
                className={cn(
                  "rounded-full px-2.5 py-0.5 text-xs font-semibold whitespace-nowrap transition-colors border cursor-pointer",
                  selectedWeek === "all"
                    ? "bg-primary text-primary-foreground border-primary"
                    : "bg-surface-2 text-muted-foreground border-border hover:bg-surface-2/80 hover:text-foreground",
                )}
              >
                All Weeks ({items.length})
              </button>
              {availableWeeks.map((wk) => {
                const count = items.filter((i) => Number(i.week_number) === wk).length;
                return (
                  <button
                    key={wk}
                    onClick={() => setSelectedWeek(wk)}
                    className={cn(
                      "rounded-full px-2 py-0.5 text-xs font-medium whitespace-nowrap transition-colors border flex items-center gap-1 cursor-pointer",
                      selectedWeek === wk
                        ? "bg-primary text-primary-foreground border-primary font-semibold"
                        : "bg-surface-2 text-muted-foreground border-border hover:bg-surface-2/80 hover:text-foreground",
                    )}
                  >
                    <span>Wk {wk}</span>
                    <span
                      className={cn(
                        "rounded-full px-1.5 py-0.2 text-[9px]",
                        selectedWeek === wk
                          ? "bg-black/20 text-white"
                          : "bg-surface text-muted-foreground",
                      )}
                    >
                      {count}
                    </span>
                  </button>
                );
              })}
            </div>

            <div className="flex items-center gap-2 shrink-0 self-end md:self-auto">
              <span className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                Sort By:
              </span>
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value as SortOption)}
                className="rounded-md border border-border bg-background px-2.5 py-1 text-xs text-foreground focus:border-primary focus:outline-none font-medium"
              >
                <option value="week_asc">Week (Chronological W1–W26)</option>
                <option value="date_asc">Date (Earliest to Latest)</option>
                <option value="priority_desc">Priority (Highest MDPS)</option>
                <option value="duration_desc">Block Duration (Longest)</option>
                <option value="block_id_asc">Block ID (A–Z)</option>
              </select>
            </div>
          </div>
        </div>

        {/* Filter Result Summary Bar */}
        <div className="flex items-center justify-between text-xs text-muted-foreground px-1 bg-surface-2/40 rounded-md p-2 border border-border/40">
          <div className="flex items-center gap-2 flex-wrap">
            <p className="font-medium text-foreground">
              Showing <strong className="text-primary font-mono font-bold">{sortedItems.length}</strong> of{" "}
              <strong className="text-foreground font-mono">{total}</strong> blocks
            </p>
            {hasActiveFilters && (
              <>
                <span className="text-muted-foreground/60">•</span>
                <span className="font-semibold text-primary/90 bg-primary/10 border border-primary/20 px-2 py-0.5 rounded text-[11px]">
                  {filterTagsSummary}
                </span>
              </>
            )}
          </div>
          {hasActiveFilters && (
            <button
              onClick={handleClearFilters}
              className="text-primary hover:underline font-semibold text-xs flex items-center gap-1 cursor-pointer shrink-0"
            >
              <X className="size-3.5" aria-hidden />
              Clear Filters
            </button>
          )}
        </div>

        {/* Loading State */}
        {loading && items.length === 0 && (
          <div className="py-20 text-center space-y-3">
            <RefreshCw className="size-8 mx-auto animate-spin text-primary" aria-hidden />
            <p className="text-sm font-medium text-foreground">Loading 26-week rolling block plan…</p>
            <p className="text-xs text-muted-foreground">Synthesizing corridor schedule from backend records</p>
          </div>
        )}

        {/* Empty State */}
        {!loading && sortedItems.length === 0 && (
          <div className="flex flex-col items-center gap-3 rounded-lg border border-border bg-surface py-20 text-center">
            <CalendarRange className="size-12 text-muted-foreground/60" aria-hidden />
            <p className="font-semibold text-base text-foreground">No matching blocks found</p>
            <p className="max-w-md text-xs text-muted-foreground">
              No rolling blocks match your current filter criteria. Try adjusting your search query, priority band,
              or date range.
            </p>
            <button
              onClick={handleClearFilters}
              className="mt-2 rounded border border-border bg-surface px-4 py-2 text-xs font-semibold text-foreground hover:bg-surface-2 transition-colors cursor-pointer"
            >
              Clear All Filters
            </button>
          </div>
        )}

        {/* Block Grid: Grouped by Week */}
        {selectedWeek === "all" && groupWeeks.length > 0 && (
          <div className="space-y-6">
            {groupWeeks.map((wk) => {
              const weekBlocks = groupedByWeek[wk] ?? [];
              const weekTotalDuration = weekBlocks.reduce(
                (acc, b) => acc + (b.duration_minutes ?? 0),
                0,
              );
              const firstBlockDate = weekBlocks[0]?.plan_date;

              return (
                <section key={wk} className="space-y-3">
                  {/* Week Group Header Banner */}
                  <div className="flex items-center justify-between gap-3 border-b border-border pb-2">
                    <div className="flex items-center gap-2">
                      <div className="flex size-6 items-center justify-center rounded-md bg-primary/10 text-primary font-mono text-xs font-bold">
                        W{wk}
                      </div>
                      <h2 className="text-sm font-bold tracking-tight text-foreground">
                        Week {wk} Maintenance Window
                      </h2>
                      {firstBlockDate && (
                        <span className="text-xs text-muted-foreground font-mono">
                          · {firstBlockDate}
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-2 text-xs text-muted-foreground">
                      <span className="rounded bg-surface-2 px-2 py-0.5 font-medium border border-border">
                        {weekBlocks.length} block{weekBlocks.length > 1 ? "s" : ""}
                      </span>
                      <span>Total: <strong className="text-foreground">{minutesToDuration(weekTotalDuration)}</strong></span>
                    </div>
                  </div>

                  {/* Cards Grid */}
                  <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
                    {weekBlocks.map((block) => (
                      <RollingBlockCard
                        key={block.block_id}
                        block={block}
                        onSelect={handleSelectBlock}
                        isSelected={selectedBlock?.block_id === block.block_id && dialogOpen}
                      />
                    ))}
                  </div>
                </section>
              );
            })}
          </div>
        )}

        {/* Block Grid: Single Week Focused View */}
        {selectedWeek !== "all" && sortedItems.length > 0 && (
          <div className="space-y-4">
            <div className="flex items-center justify-between gap-3 border-b border-border pb-3">
              <div className="flex items-center gap-2">
                <div className="flex size-7 items-center justify-center rounded-md bg-primary text-primary-foreground font-mono text-sm font-bold">
                  W{selectedWeek}
                </div>
                <div>
                  <h2 className="text-base font-bold text-foreground">
                    Week {selectedWeek} Operational Maintenance Windows
                  </h2>
                  <p className="text-xs text-muted-foreground">
                    {sortedItems.length} blocks scheduled for execution in Week {selectedWeek}
                  </p>
                </div>
              </div>
              <span className="text-xs text-muted-foreground">
                Total Allocated Time:{" "}
                <strong className="text-foreground font-mono">
                  {minutesToDuration(
                    sortedItems.reduce((acc, b) => acc + (b.duration_minutes ?? 0), 0),
                  )}
                </strong>
              </span>
            </div>

            <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
              {sortedItems.map((block) => (
                <RollingBlockCard
                  key={block.block_id}
                  block={block}
                  onSelect={handleSelectBlock}
                  isSelected={selectedBlock?.block_id === block.block_id && dialogOpen}
                />
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Detailed Block Inspection Modal */}
      <RollingBlockDetailDialog
        block={selectedBlock}
        open={dialogOpen}
        onOpenChange={handleDialogOpenChange}
        onStatusUpdated={handleStatusUpdated}
      />

      {/* Manual Create Block Modal — full AI pipeline evaluation */}
      <CreateBlockModal
        open={createBlockModalOpen}
        onOpenChange={setCreateBlockModalOpen}
        defaultWeek={typeof selectedWeek === "number" ? selectedWeek : 17}
        onBlockCreated={() => void fetchData()}
      />
    </div>
  );
}
