/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppLiveRouteImport } from './routes/_app/live'
import { Route as AppPlannerRouteImport } from './routes/_app/planner'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppResourcesRouteImport } from './routes/_app/resources'
import { Route as AppDisruptionsIndexRouteImport } from './routes/_app/disruptions/index'
import { Route as AppDisruptionsEventIdRouteImport } from './routes/_app/disruptions/$eventId'
import { Route as AppRecommendationsIndexRouteImport } from './routes/_app/recommendations/index'
import { Route as AppRecommendationsRecommendationIdRouteImport } from './routes/_app/recommendations/$recommendationId'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks/$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppDisruptionsIndexRoute = AppDisruptionsIndexRouteImport.update({
  id: '/disruptions/',
  path: '/disruptions/',
  getParentRoute: () => AppRoute,
} as any)
const AppDisruptionsEventIdRoute = AppDisruptionsEventIdRouteImport.update({
  id: '/disruptions/$eventId',
  path: '/disruptions/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsIndexRoute = AppRecommendationsIndexRouteImport.update({
  id: '/recommendations/',
  path: '/recommendations/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRecommendationIdRoute =
  AppRecommendationsRecommendationIdRouteImport.update({
    id: '/recommendations/$recommendationId',
    path: '/recommendations/$recommendationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/live': typeof AppLiveRoute
  '/planner': typeof AppPlannerRoute
  '/reports': typeof AppReportsRoute
  '/resources': typeof AppResourcesRoute
  '/disruptions/$eventId': typeof AppDisruptionsEventIdRoute
  '/recommendations/$recommendationId': typeof AppRecommendationsRecommendationIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/disruptions/': typeof AppDisruptionsIndexRoute
  '/recommendations/': typeof AppRecommendationsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/live': typeof AppLiveRoute
  '/planner': typeof AppPlannerRoute
  '/reports': typeof AppReportsRoute
  '/resources': typeof AppResourcesRoute
  '/disruptions/$eventId': typeof AppDisruptionsEventIdRoute
  '/recommendations/$recommendationId': typeof AppRecommendationsRecommendationIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/disruptions': typeof AppDisruptionsIndexRoute
  '/recommendations': typeof AppRecommendationsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/live': typeof AppLiveRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/disruptions/$eventId': typeof AppDisruptionsEventIdRoute
  '/_app/recommendations/$recommendationId': typeof AppRecommendationsRecommendationIdRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/disruptions/': typeof AppDisruptionsIndexRoute
  '/_app/recommendations/': typeof AppRecommendationsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/live'
    | '/planner'
    | '/reports'
    | '/resources'
    | '/disruptions/$eventId'
    | '/recommendations/$recommendationId'
    | '/tasks/$taskId'
    | '/disruptions/'
    | '/recommendations/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/live'
    | '/planner'
    | '/reports'
    | '/resources'
    | '/disruptions/$eventId'
    | '/recommendations/$recommendationId'
    | '/tasks/$taskId'
    | '/disruptions'
    | '/recommendations'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/live'
    | '/_app/planner'
    | '/_app/reports'
    | '/_app/resources'
    | '/_app/disruptions/$eventId'
    | '/_app/recommendations/$recommendationId'
    | '/_app/tasks/$taskId'
    | '/_app/disruptions/'
    | '/_app/recommendations/'
    | '/_app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disruptions/': {
      id: '/_app/disruptions/'
      path: '/disruptions'
      fullPath: '/disruptions/'
      preLoaderRoute: typeof AppDisruptionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disruptions/$eventId': {
      id: '/_app/disruptions/$eventId'
      path: '/disruptions/$eventId'
      fullPath: '/disruptions/$eventId'
      preLoaderRoute: typeof AppDisruptionsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations/': {
      id: '/_app/recommendations/'
      path: '/recommendations'
      fullPath: '/recommendations/'
      preLoaderRoute: typeof AppRecommendationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations/$recommendationId': {
      id: '/_app/recommendations/$recommendationId'
      path: '/recommendations/$recommendationId'
      fullPath: '/recommendations/$recommendationId'
      preLoaderRoute: typeof AppRecommendationsRecommendationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLiveRoute: typeof AppLiveRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppDisruptionsEventIdRoute: typeof AppDisruptionsEventIdRoute
  AppRecommendationsRecommendationIdRoute: typeof AppRecommendationsRecommendationIdRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppDisruptionsIndexRoute: typeof AppDisruptionsIndexRoute
  AppRecommendationsIndexRoute: typeof AppRecommendationsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLiveRoute: AppLiveRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppReportsRoute: AppReportsRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppDisruptionsEventIdRoute: AppDisruptionsEventIdRoute,
  AppRecommendationsRecommendationIdRoute:
    AppRecommendationsRecommendationIdRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppDisruptionsIndexRoute: AppDisruptionsIndexRoute,
  AppRecommendationsIndexRoute: AppRecommendationsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
